name: Deploy Daily Report to GitHub Pages

on:
  schedule:
    - cron: '40 22 * * *'  # 每天台灣時間早上 06:40 自動執行
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Latest Report from Google Drive
        run: curl -L "https://drive.google.com/uc?export=download&id=1TAHe97Io5ESTYi2lxQWFkuJ5QqrO2uxk" -o index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
